# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST https://localhost:5001/api/ApplicationUser/Verify
Content-Type: application/json

{
  "userName": "zouxuan",
  "password": "abc&ABC12"
}

### Password grant type

POST https://localhost:7001/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=ijoozClientId&client_secret=ijoozClientIdSecret&scope=ijooz&username=zouxuan&password=abc&ABC12


### Refresh Token

POST https://localhost:7001/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&client_id=ijoozClientId&client_secret=ijoozClientIdSecret&refresh_token=1e2696524b51d3de026995246a9cd56ccf43f60ccee3aad13fa2d3a9f56cebc9



### Client Credential

POST https://localhost:7001/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=thirdParty&client_secret=thirdPartySecret&scope=ijooz

